// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvlsgmyzityxlulpuuhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bHNnbXl6aXR5eGx1bHB1dWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4ODk0MjMsImV4cCI6MjA1MzQ2NTQyM30.YobERdtQPIJpaCBqraXbvBRotl269VsITRo0WzGO2v8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);